#!/usr/bin/env bash
#Install nginx and set a default message on port 80 as default

sudo apt-get update -y
sudo apt install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
