#!/usr/bin/env bash
# Displays "Best School" 10 times
#+ but for the 9th iteration, displays Best School then Hi

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
